const pokelist = [
    {name: 'Arcanine'},
    {name: 'Beedrill'},
    {name: 'Blastoise'},
    {name: 'Bulbasaur'},
    {name: 'Butterfree'},
    {name: 'Caterpie'},
    {name: 'Charizard'},
    {name: 'Charmander'},
    {name: 'Charmeleon'},
    {name: 'Clefable'},
    {name: 'Dewgong'},
    {name: 'Farfetchd'},
    {name: 'Golbat'},
    {name: 'Ivysaur'},
    {name: 'Kadabra'},
    {name: 'Kakuna'},
    {name: 'Metapod'},
    {name: 'Pidgeot'},
    {name: 'Pidgeotto'},
    {name: 'Pidgey'},
    {name: 'Pikachu'},
    {name: 'Ponyta'},
    {name: 'Raichu'},
    {name: 'Raticate'},
    {name: 'Rattata'},
    {name: 'Squirtle'},
    {name: 'Venusaur'},
    {name: 'Vulpix'},
    {name: 'Wartortle'},
    {name: 'Weedle'},
]

export default pokelist